shim-version: v0.3.9@sha256:a45eb01f8e5fa3162b804821d53d8e8667a75940a9c1995f29265347efca8009
cvm-version: 0.5.18
cpus: 2
memory: 8192

containers:
  - name: "compatibility-enclave"
    image: ""
    args:
      - "-e"
      - "OPENAI_API_KEY=$(awk -F': *' '$1~/^openai-api-key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)"
      - "rkdud007/enclave:latest@sha256:a488ce2907b60f18659f5d5690f84d1b7c8b1acf03dcbd0559d331301656c357"

shim:
  listen-port: 443
  upstream-port: 8001
  paths:
    - /evaluate
    - /health
    - /upload/*
