shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.6
cpus: 2
memory: 8192

containers:
  - name: "compatibility-enclave"
    image: "rkdud007/enclave:latest@sha256:a488ce2907b60f18659f5d5690f84d1b7c8b1acf03dcbd0559d331301656c357"
    secrets:
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8001
  paths:
    - /evaluate
    - /health
    - /upload/*
