shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.6.7
cpus: 2
memory: 8192

containers:
  - name: "ndai-enclave"
    image: "rkdud007/ndai-zone:latest@sha256:d2e3a78a9ea7be7bb041195dbc903f601175c950eee03cc6dd06d173b9b1a37e"
    secrets:
      - TINFOIL_API_KEY
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
    - /verification
    - /register
    - /rooms/*
