shim-version: v0.3.9@sha256:a45eb01f8e5fa3162b804821d53d8e8667a75940a9c1995f29265347efca8009
cvm-version: 0.5.18
cpus: 2
memory: 8192

containers:
  - name: "compatibility-enclave"
    image: ""
    args:
      - "-e"
      - "OPENAI_API_KEY=$(awk -F': *' '$1~/^openai-api-key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)"
      - "rkdud007/enclave:latest@sha256:20614da74021dc2b9fbbfbbbb6209e960dd764d8247955a3075ddc533d6d76c6"
      - "--port"
      - "8001"

shim:
  listen-port: 443
  upstream-port: 8001
  paths:
    - /evaluate
    - /health
    - /upload/*
