shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.6
cpus: 2
memory: 8192

containers:
  - name: "ndai-enclave"
    image: "rkdud007/ndai-zone:latest@sha256:ae26837ba4d20fef77bfa405e5a42c0b8e920427487ad2eea1b5dee082db705e"
    secrets:
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8001
  paths:
    - /health
    - /register
    - /rooms/*
