shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.6
cpus: 2
memory: 8192

containers:
  - name: "ndai-enclave"
    image: "rkdud007/ndai-zone:latest@sha256:34aaa585254fddfe6d47f8f047dac19e976c416fa0b6532efd1bae63a02b8951"
    secrets:
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
    - /register
    - /rooms/*
