shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.6
cpus: 2
memory: 8192

containers:
  - name: "ndai-enclave"
    image: "rkdud007/ndai-zone:latest@sha256:0006943eb0ce03a5afcf3291afe100f7f6fae70a4a95ff8b8b766fe43848270c"
    secrets:
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
    - /register
    - /rooms/*
