shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.6
cpus: 2
memory: 8192

containers:
  - name: "ndai-enclave"
    image: "rkdud007/ndai-zone:latest@sha256:b2092c25413cac75bcd0479a8773ec081006abe37438f86b37d4be11eb6bc226"
    secrets:
      - OPENAI_API_KEY

shim:
  listen-port: 443
  upstream-port: 8000
  paths:
    - /health
    - /register
    - /rooms/*
